
#############################
# Workspaces
#############################
workspace = 1, monitor:DP-3
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3
workspace = 6, monitor:DP-3
workspace = 7, monitor:DP-3
workspace = 8, monitor:DP-3
workspace = 9, monitor:DP-3
workspace = 10, monitor:DP-3

workspace = 11, monitor:HDMI-A-1
workspace = 12, monitor:HDMI-A-1
workspace = 13, monitor:HDMI-A-1
workspace = 14, monitor:HDMI-A-1
workspace = 15, monitor:HDMI-A-1
workspace = 16, monitor:HDMI-A-1
workspace = 17, monitor:HDMI-A-1
workspace = 18, monitor:HDMI-A-1
workspace = 19, monitor:HDMI-A-1
workspace = 20, monitor:HDMI-A-1

#############################
# App placement
#############################
windowrule = match:class discord, workspace 17 silent
windowrule = match:class steam, workspace 8 silent
windowrule = match:class code, workspace 7 silent

#############################
# Float tools
#############################
windowrule = match:class wofi, float on
windowrule = match:class org.pulseaudio.pavucontrol, float on

#############################
# Behaviour
#############################
windowrule = match:class .*, suppress_event maximize


windowrule = match:class ^ulauncher$, float on
windowrule = match:class ^ulauncher$, stay_focused on
windowrule = match:class ^ulauncher$, border_size 0
windowrule = match:class ^ulauncher$, no_shadow on
windowrule = match:class ^ulauncher$, no_blur on
windowrule = match:class ^ulauncher$, size 50% 60%
windowrule = match:class ^ulauncher$, center on
